SELECT PROJECT.ID AS NAME,
SUM(SALARY * DATEDIFF (month, START_DATE, FINISH_DATE)) AS PRICE
FROM PROJECT_WORKER
JOIN WORKER
ON PROJECT_WORKER.WORKER_ID = WORKER.ID
JOIN PROJECT
ON PROJECT_WORKER.PROJECT_ID = PROJECT.ID
GROUP BY PROJECT.ID
ORDER BY PRICE DESC